Week1 xiaoxue shen
TAIsRich/chuwa4.1-Coding pull request #71
Opened 2022-04-29 18:01 UTC by shirleyshen06

2022-05-02 06:38 UTC, TAIsRich requested changes

2022-05-02 06:38 UTC, TAIsRich commented on springboot-user(1)/src/main/java/com/chuwa/service/impl/UserServiceImpl.java
> +    public User addUser(User user) {
请添加user的验证，然后再save，
user == null?
user 没有password？
if ( user  == null || user.getPassword == null) {
throw exception();
}

2022-05-03 21:09 UTC, TAIsRich requested changes

2022-05-03 21:09 UTC, TAIsRich commented on springboot-user(2)/src/main/java/com/chuwa/controller/userController.java
> +    @DeleteMapping("delete/{id}")
api命名有问题。
/users/{id}

2022-05-03 21:09 UTC, TAIsRich commented on springboot-user(2)/src/main/java/com/chuwa/controller/userController.java
> +    @PutMapping("/update")
/users/{id}

2022-05-03 21:09 UTC, TAIsRich commented on springboot-user(2)/src/main/java/com/chuwa/controller/userController.java
> +    @GetMapping("/find/{email}")
/users/{email}

2022-05-03 22:47 UTC, shirleyshen06 commented on springboot-user(2)/src/main/java/com/chuwa/controller/userController.java
> +    @GetMapping("/find/{email}")
<img width="291" alt="Screen Shot 2022-05-03 at 3 46 26 PM" src="https://user-images.githubusercontent.com/77641343/166585226-7add1a43-525e-4f66-a945-55c5fc2f7ba6.png">
@RequestMapping("/user").   at top ,why I have to add "user" again ?

2022-05-05 16:19 UTC, merged